//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaYonetimSistemi_HYS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneYonetimSistemiEntities : DbContext
    {
        public HastaneYonetimSistemiEntities()
            : base("name=HastaneYonetimSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDoktor> TblDoktor { get; set; }
        public virtual DbSet<TblHasta> TblHasta { get; set; }
        public virtual DbSet<TblSonuclar> TblSonuclar { get; set; }
    }
}
