//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaYonetimSistemi_HYS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHasta
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Cinsiyet { get; set; }
        public string KanGrubu { get; set; }
        public string Hastalık { get; set; }
    }
}
