//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaYonetimSistemi_HYS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSonuclar
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Belirtiler { get; set; }
        public string Ilaclar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> HastaID { get; set; }
    }
}
